### ISSUE TITLE
Comparison method violates its general contract!

### ISSUE THREAD

**Issue by drdickens** [diwi/Space_Partitioning_Octree_BVH#1]
java 1.7 throws this exception:

```
> start building
```

Exception in thread "Animation Thread" java.lang.IllegalArgumentException: Comparison method violates its general contract!
    at java.util.TimSort.mergeLo(TimSort.java:747)
    at java.util.TimSort.mergeAt(TimSort.java:483)
    at java.util.TimSort.mergeCollapse(TimSort.java:410)
    at java.util.TimSort.sort(TimSort.java:214)
    at java.util.TimSort.sort(TimSort.java:173)
    at java.util.Arrays.sort(Arrays.java:659)
    at java.util.Collections.sort(Collections.java:217)
    at DwBVH.BvhBuilder.subdivide(BvhBuilder.java:87)
    at DwBVH.BvhBuilder.subdivide(BvhBuilder.java:122)
    at DwBVH.BvhBuilder.subdivide(BvhBuilder.java:122)
    at DwBVH.BvhBuilder.subdivide(BvhBuilder.java:121)
    at DwBVH.BvhBuilder.subdivide(BvhBuilder.java:121)
    at DwBVH.BvhBuilder.BUILD_defaultRoutine(BvhBuilder.java:66)
    at DwBVH.Bvh.BUILD_defaultRoutine(Bvh.java:62)
    at SpacePartitioning.MAIN_bvh_octree_demo.setup(MAIN_bvh_octree_demo.java:144)
    at processing.core.PApplet.handleDraw(Unknown Source)
    at processing.core.PApplet.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:744)

**Comment by diwi** [comment]
the exception was due to a change from java 6 to java 7.
it is fixed now...

**Comment by nomutenvision** [comment]
Thomas,
sorry if I leave a comment in here, but I do not find a way to subscribe (Create Account), to your blog, expecially I would like to partecipate to discussion regarding blog (blog/?page_id=91).
But where is the link to create an account for your blog ?
